name: Daily Blog Generator

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate_blog:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access for pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use default token with write permissions

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate blog content
        run: python generate_blog.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes
        run: |
          git add posts/
          git commit -m "Auto-generated blog for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main
